const sections=['Overview','Rates','Inflation','Labor','Growth','Consumer','Corporate','Financial Conditions','Liquidity','Treasury & Fiscal'];
let db={metrics:[]},active='Overview',chart=null;
const fmt=(v,u)=>{if(v==null)return '—'; if(u==='%')return v.toFixed(2)+'%'; if(u==='pp')return v.toFixed(2)+' pp'; if(u==='claims')return Math.round(v).toLocaleString(); if(u.includes('$'))return '$'+v.toLocaleString(undefined,{maximumFractionDigits:1}); return v.toLocaleString(undefined,{maximumFractionDigits:2})};
function score(){let m=db.metrics.filter(x=>x.importance>=4); if(!m.length)return 50; let s=50;m.forEach(x=>s+=x.status==='positive'?x.importance*.7:x.status==='negative'?-x.importance*.7:0);return Math.max(0,Math.min(100,Math.round(s)))}
function setupNav(){nav.innerHTML=sections.map(s=>`<button data-s="${s}" class="${s===active?'active':''}">${s}</button>`).join('');nav.querySelectorAll('button').forEach(b=>b.onclick=()=>{active=b.dataset.s;setupNav();render()})}
function card(x){let arrow=x.change>0?'▲':x.change<0?'▼':'–';return `<article class="card" data-id="${x.id}"><div class="top"><strong>${x.name}</strong><span class="importance">${'★'.repeat(x.importance)}</span></div><div class="value">${fmt(x.value,x.unit)}</div><div class="change ${x.status}">${arrow} ${x.change==null?'—':Math.abs(x.change).toFixed(2)}</div><div class="date">as of ${x.date} · ${x.frequency||'FRED'}</div></article>`}
function render(){let q=search.value.toLowerCase();let m=db.metrics.filter(x=>(active==='Overview'?x.importance>=5:x.section===active)&&x.name.toLowerCase().includes(q));content.innerHTML=`<div class="section-title"><div><span class="label">${active.toUpperCase()}</span><h3>${active==='Overview'?'Highest-impact indicators':active}</h3></div><span class="muted">${m.length} indicators</span></div><div class="cards">${m.map(card).join('')}</div><div class="chart-wrap"><canvas id="detailChart"></canvas></div>`; content.querySelectorAll('.card').forEach(c=>c.onclick=()=>draw(c.dataset.id)); if(m[0])draw(m[0].id)}
function draw(id){let x=db.metrics.find(m=>m.id===id);if(!x)return;let ctx=document.getElementById('detailChart'); if(chart)chart.destroy();chart=new Chart(ctx,{type:'line',data:{labels:x.history.map(a=>a.date),datasets:[{label:x.name,data:x.history.map(a=>a.value),borderWidth:2,pointRadius:0,tension:.15}]},options:{responsive:true,maintainAspectRatio:false,plugins:{legend:{labels:{color:'#cbd3e1'}}},scales:{x:{ticks:{color:'#788295',maxTicksLimit:9},grid:{color:'#202633'}},y:{ticks:{color:'#788295'},grid:{color:'#202633'}}}}})}
async function load(){try{let r=await fetch('data/latest.json?'+Date.now());db=await r.json();updated.textContent='Last data build: '+new Date(db.generated_at).toLocaleString();let s=score();document.getElementById('score').textContent=s;regime.textContent=s>=70?'Supportive / Risk-On':s<=35?'Restrictive / Risk-Off':'Balanced / Mixed';setupNav();render()}catch(e){updated.textContent='No live data yet — run the updater or GitHub Action.'}}
search.oninput=render;refresh.onclick=load;load();
